# fly.toml app configuration file generated for cold-meadow-4842 on 2023-08-06T13:33:15+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-meadow-4842"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
